### ISSUE TITLE
Some of the images are not showing in production

### ISSUE THREAD

**Issue by mmdonaldson** [Massey-7-Wonders-project-team/Massey_Project_7_Wonders#114]
Need to investigate whether this is a routing issue or an issue with part of our webpack front end build

**Comment by jacobstringer** [comment]
What browser is this on?

**Comment by mmdonaldson** [comment]
Chrome on OSX

**Comment by mmdonaldson** [comment]
Henning had this issue on linux too. It's because we are referencing images in the code as .png but the files are named .PNG. Adding a PR for this soon.

**Comment by mmdonaldson** [comment]
Fix for it here PR #121 https://github.com/Massey-7-Wonders-project-team/Massey_Project_7_Wonders/pull/121
