### ISSUE TITLE
Problems going between active game and game instructions

### ISSUE THREAD

**Issue by jacobstringer** [Massey-7-Wonders-project-team/Massey_Project_7_Wonders#160]
User test report:
- User went from active game to the game instructions.
- User pressed back button
- Game flickered between play screen and setup game screen and was unresponsive to button pushes

The only way for the user to fix the issue was to close the tab and start a new game on another tab.

**Comment by mmdonaldson** [comment]
I think the fix may be to ensure when the user navigates away from the play screen we need to clear the polling interval

**Comment by mmdonaldson** [comment]
@jacobstringer i just repeated this and seems to have been fixed. Closing for now. Reopen if we see it again
