### ISSUE TITLE
Tests failing in CI

### ISSUE THREAD

**Issue by mmdonaldson** [Massey-7-Wonders-project-team/Massey_Project_7_Wonders#192]
Tests seem to be failing in CircleCI but not locally.

The only thing I can think of is the python version in circleci is 3.4.5 but 3.6.1 is what i run locally

**Comment by mmdonaldson** [comment]
The other interesting thing is that it is inconsistent. Sometimes it passes, sometimes it fails 1, sometimes 7, sometimes 8.

**Comment by jacobstringer** [comment]
https://github.com/Massey-7-Wonders-project-team/Massey_Project_7_Wonders/pull/193 has solved this issue.
