### ISSUE TITLE
Doubled cards given

### ISSUE THREAD

**Issue by jacobstringer** [Massey-7-Wonders-project-team/Massey_Project_7_Wonders#31]
127.0.0.1 - - [14/Aug/2017 16:01:53] "POST /api/create_user HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:01:53] "GET /api/user HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:01:55] "GET /api/game/check HTTP/1.1" 200 -
user:  11
127.0.0.1 - - [14/Aug/2017 16:01:55] "GET /api/game/create HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:01:55] "GET /api/game/status?player_id=3 HTTP/1.1" 200 -
[<application.models.player.Player object at 0x0000023D4999D860>, <application.models.player.Player object at 0x0000023D4999DB38>, <application.models.player.Player object at 0x0000023D499D1908>]
127.0.0.1 - - [14/Aug/2017 16:01:56] "GET /api/game/start?player_id=3 HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:01:56] "GET /src/components/cards/lumberyard.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:01:56] "GET /src/components/cards/glassworks.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:01:56] "GET /src/components/cards/marketplace.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:01:56] "GET /src/components/cards/altar.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:01:56] "GET /src/components/cards/barracks.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:01:56] "GET /src/components/cards/apothecary.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:01:56] "GET /src/components/cards/workshop.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:57] "GET /play HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:57] "GET /play HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:57] "GET /play HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:57] "GET /play HTTP/1.1" 200 -
[<application.models.player.Player object at 0x0000023D49B51390>, <application.models.player.Player object at 0x0000023D49B440B8>, <application.models.player.Player object at 0x0000023D49B442E8>]
127.0.0.1 - - [14/Aug/2017 16:02:57] "GET /api/game/start?player_id=1 HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:57] "GET /dist/bundle.css HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:57] "GET /dist/bundle.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "POST /api/is_token_valid HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "POST /api/is_token_valid HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /api/game/check HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /src/images/favicon.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /api/game/status?player_id=2 HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /api/game/check HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /api/game/status?player_id=1 HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /images/cards/lumberyard.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /images/cards/orevein.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /images/cards/claypool.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /images/cards/stonepit.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /images/cards/timberyard.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /images/cards/loom.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /images/cards/easttradingpost.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /images/cards/theatre.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /images/cards/baths.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /images/cards/stockade.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /images/cards/guardtower.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /images/cards/workshop.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /images/cards/scriptorium.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:58] "GET /src/components/cards/claypool.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:59] "GET /src/components/cards/claypit.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:59] "GET /src/components/cards/stonepit.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:59] "GET /src/components/cards/timberyard.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:59] "GET /src/components/cards/glassworks.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:59] "GET /src/components/cards/press.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:59] "GET /src/components/cards/easttradingpost.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:59] "GET /src/components/cards/westtradingpost.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:59] "GET /src/components/cards/altar.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:59] "GET /src/components/cards/theatre.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:59] "GET /src/components/cards/barracks.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:59] "GET /src/components/cards/apothecary.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:02:59] "GET /src/components/cards/scriptorium.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:55] "GET /play HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:56] "GET /dist/bundle.css HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:56] "GET /dist/bundle.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:56] "POST /api/is_token_valid HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:57] "GET /api/game/check HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:57] "GET /api/game/status?player_id=2 HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:57] "GET /images/cards/lumberyard.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:57] "GET /images/cards/orevein.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:57] "GET /images/cards/claypool.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:57] "GET /images/cards/stonepit.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:57] "GET /images/cards/timberyard.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:57] "GET /images/cards/loom.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:57] "GET /images/cards/easttradingpost.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:57] "GET /images/cards/theatre.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:57] "GET /images/cards/baths.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:57] "GET /images/cards/stockade.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:57] "GET /images/cards/guardtower.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:57] "GET /images/cards/workshop.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:19:57] "GET /images/cards/scriptorium.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:13] "GET /play HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:13] "GET /dist/bundle.css HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:21] "GET /play HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:21] "GET /dist/bundle.css HTTP/1.1" 304 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "GET /dist/bundle.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "POST /api/is_token_valid HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "GET /api/game/check HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "GET /api/game/status?player_id=3 HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "GET /images/cards/lumberyard.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "GET /images/cards/orevein.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "GET /images/cards/claypit.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "GET /images/cards/loom.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "GET /images/cards/glassworks.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "GET /images/cards/press.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "GET /images/cards/marketplace.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "GET /images/cards/altar.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "GET /images/cards/baths.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "GET /images/cards/stockade.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "GET /images/cards/barracks.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "GET /images/cards/apothecary.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:22] "GET /images/cards/workshop.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:35] "GET /play HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:35] "POST /api/is_token_valid HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:35] "GET /api/game/check HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:35] "GET /src/images/favicon.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:35] "GET /api/game/status?player_id=1 HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:36] "GET /src/components/cards/easttradingpost.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:36] "GET /src/components/cards/westtradingpost.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:36] "GET /src/components/cards/claypool.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:36] "GET /src/components/cards/stonepit.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:36] "GET /src/components/cards/timberyard.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:36] "GET /src/components/cards/claypit.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:36] "GET /src/components/cards/glassworks.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:36] "GET /src/components/cards/press.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:36] "GET /src/components/cards/altar.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:36] "GET /src/components/cards/theatre.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:36] "GET /src/components/cards/barracks.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:36] "GET /src/components/cards/apothecary.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Aug/2017 16:20:36] "GET /src/components/cards/scriptorium.png HTTP/1.1" 200 -

![image](https://user-images.githubusercontent.com/29744668/29258474-01afc778-810e-11e7-8489-07cbbe7fbc7e.png)

**Comment by mmdonaldson** [comment]
I can't seem to reproduce this locally

**Comment by mmdonaldson** [comment]
Closing as seems issue has gone @jacobstringer
