### ISSUE TITLE
Cards dealt not showing.

### ISSUE THREAD

**Issue by wackydapper** [Massey-7-Wonders-project-team/Massey_Project_7_Wonders#39]
Once in game screen with 3 or more players, cards are not displaying.

- this is only happening in a development environment, production shows cards fine.

- need to refactor how webpacks build tooling routes our static images

**Comment by mmdonaldson** [comment]
Cannot fix yet as blocked by bug #46

**Comment by mmdonaldson** [comment]
Closing as seems to have been fixed.
