### ISSUE TITLE
How do you delete a folder in github?

### ISSUE THREAD

**Issue by Marthijn-B** [Massey-7-Wonders-project-team/Massey_Project_7_Wonders#51]
There is an icon folder in the main folder that is not needed (ie stored in the wrong place) I have submitted a new folder in the correct place. 
Could someone delete the previously uploaded icon folder in the following location:
`Massey_Project_7_Wonders/icons/`

Thanks
Marthijn

**Comment by mmdonaldson** [comment]
No worries I have deleted in the PR I am working on, will close this issue once i push PR in a day or two.

In terms of how to delete something on github, how are you pushing things to github?

In the command line:
- delete the folder you want to delete
- ensure nothing else has changed to commit
- `git add --all` will commit all of the deleted files.
- `git commit -m "message"`
- `git push origin branch`

**Comment by mmdonaldson** [comment]
Fixed in PR #52
