### ISSUE TITLE
Old players still polling

### ISSUE THREAD

**Issue by jacobstringer** [Massey-7-Wonders-project-team/Massey_Project_7_Wonders#83]
When a game is ended, and a new one gets started, the old player id is still polling the server currently. The only way to stop this is to close the tab and open a new tab.

**Comment by mmdonaldson** [comment]
I should have fixed this in a previous PR. When you click the 'end game' button the interval should be cleared @jacobstringer

**Comment by jacobstringer** [comment]
After pressing the end game button, it was still happening for me.

**Comment by Marthijn-B** [comment]
Solved
PR #92
